steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Prepare'
  args:
  - kms
  - decrypt
  - --ciphertext-file=builds_rsa_prod.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=builds-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: "golang:1.14"
  id: 'Build'
  entrypoint: "bash"
  args:
    - "-c"
    - |
      ssh-keyscan github.com > /root/.ssh/known_hosts
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      chmod 0600 /root/.ssh/id_rsa
      GOOS=linux CGO_ENABLED=0 go build -a -installsuffix cgo -o ./go/bin/orchard
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker Build'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/loupe-prod/orchard:$TAG_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "gcr.io/loupe-prod/orchard"]

images:
- '$_IMAGE_NAME:$TAG_NAME'
substitutions:
  _IMAGE_NAME: 'gcr.io/loupe-prod/orchard'
options:
  substitution_option: 'ALLOW_LOOSE'
  env:
  - GO111MODULE=on
  volumes:
  - name: go-modules
    path: /go
tags: ['gcp-cloud-build-deploy', '$_K8S_APP_NAME']




