// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ConnectorConfig string
	CRMRole         string
	Group           string
	GroupViewer     string
	LinkedAccount   string
	Person          string
	SystemRole      string
	Tenant          string
}{
	ConnectorConfig: "connector_config",
	CRMRole:         "crm_role",
	Group:           "group",
	GroupViewer:     "group_viewer",
	LinkedAccount:   "linked_account",
	Person:          "person",
	SystemRole:      "system_role",
	Tenant:          "tenant",
}
