// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("models: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

// Enum values for connector_config_type
const (
	ConnectorConfigTypeSalesforce = "salesforce"
	ConnectorConfigTypeHubspot    = "hubspot"
)

// Enum values for group_type
const (
	GroupTypeInternal = "internal"
	GroupTypeManager  = "manager"
	GroupTypeIc       = "ic"
)

// Enum values for group_status
const (
	GroupStatusActive   = "active"
	GroupStatusInactive = "inactive"
)

// Enum values for linked_account_status
const (
	LinkedAccountStatusActive  = "active"
	LinkedAccountStatusDeleted = "deleted"
	LinkedAccountStatusPending = "pending"
	LinkedAccountStatusErrored = "errored"
)

// Enum values for person_status
const (
	PersonStatusActive   = "active"
	PersonStatusInactive = "inactive"
)

// Enum values for person_type
const (
	PersonTypeInternal = "internal"
	PersonTypeManager  = "manager"
	PersonTypeIc       = "ic"
)

// Enum values for system_role_type
const (
	SystemRoleTypeInternal = "internal"
	SystemRoleTypeManager  = "manager"
	SystemRoleTypeIc       = "ic"
)

// Enum values for system_role_status
const (
	SystemRoleStatusActive   = "active"
	SystemRoleStatusInactive = "inactive"
)

// Enum values for tenant_status
const (
	TenantStatusActive  = "active"
	TenantStatusDeleted = "deleted"
	TenantStatusPending = "pending"
	TenantStatusExpired = "expired"
)

// Enum values for group_sync_status
const (
	GroupSyncStatusActive     = "active"
	GroupSyncStatusPeopleOnly = "people_only"
	GroupSyncStatusInactive   = "inactive"
)
