// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CRMRoles", testCRMRolesUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("GroupViewers", testGroupViewersUpsert)

	t.Run("LinkedAccounts", testLinkedAccountsUpsert)

	t.Run("People", testPeopleUpsert)

	t.Run("SystemRoles", testSystemRolesUpsert)

	t.Run("Tenants", testTenantsUpsert)
}
