apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchard
  labels:
    app: orchard
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchard
  template:
    metadata:
      labels:
        app: orchard
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
        - name: app-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "orchard"
      containers:
        - name: orchard
          image: gcr.io/loupe-dev/orchard:latest
          ports:
            - name: grpc-server
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: orchard
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: BQ_TIER_REALTIME
              valueFrom:
                configMapKeyRef:
                  name: bigquery-client
                  key: bq.tier.realtime
            - name: BQ_TIER_FRONTLINE
              valueFrom:
                configMapKeyRef:
                  name: bigquery-client
                  key: bq.tier.frontline
            - name: BQ_TIER_CORE
              valueFrom:
                configMapKeyRef:
                  name: bigquery-client
                  key: bq.tier.core
            - name: BQ_TIER_ETL
              valueFrom:
                configMapKeyRef:
                  name: bigquery-client
                  key: bq.tier.etl
            - name: BQ_TIER_BACKGROUND
              valueFrom:
                configMapKeyRef:
                  name: bigquery-client
                  key: bq.tier.background
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: app-secrets
              mountPath: "/var/app-secrets"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
