[psql]
  dbname = "tenant"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass = "jLariybb1oe5FbDz"
  whitelist = ["crm_role", "group", "group_viewer", "linked_account", "person", "system_role", "tenant"]
  sslmode = "disable"